train:
  dataset: clutrr
  model: gpt-3.5-turbo-0613
  prompt: prompt/clutrr/symbolic/5-shot_cot_htt_train.yaml

test:
  dataset: clutrr
  model: gpt-3.5-turbo-0613
  prompt: prompt/clutrr/symbolic/5-shot_cot_htt_test.yaml
  library: checkpoint/clutrr/symbolic/gpt-3.5_5-shot_cot_htt_2000.yaml
  min_coverage: 2
  min_confidence: 0.3