train:
  dataset: list_functions
  model: gemini-pro
  prompt: prompt/list_functions/4-shot_cot_htt_train.yaml

test:
  dataset: list_functions
  model: gemini-pro
  prompt: prompt/list_functions/4-shot_cot_htt_test.yaml
  library: checkpoint/list_functions/gemini-pro_4-shot_cot_htt_5000.yaml
  min_coverage: 1
  min_confidence: 0.3