train:
  dataset: base-16
  model: gpt-4
  prompt: prompt/arithmetic/base-16/5-shot_cot_htt_train.yaml

test:
  dataset: base-16
  model: gpt-4
  max_tokens: 1000
  prompt: prompt/arithmetic/base-16/5-shot_cot_htt_test.yaml
  library: checkpoint/arithmetic/base-16/gpt-4_5-shot_cot_htt_2000.yaml
  min_coverage: 2
  min_confidence: 0.5