train:
  dataset: base-9
  model: gpt-4
  prompt: prompt/arithmetic/base-9/5-shot_cot_htt_train.yaml

test:
  dataset: base-9
  model: gpt-4
  prompt: prompt/arithmetic/base-9/5-shot_cot_htt_test.yaml
  library: checkpoint/arithmetic/base-9/gpt-4_5-shot_cot_htt_2000.yaml
  min_coverage: 2
  min_confidence: 0.3