train:
  dataset: base-9
  model: gpt-3.5-turbo-0613
  prompt: prompt/arithmetic/base-9/5-shot_cot_htt_train.yaml

test:
  dataset: base-9
  model: gpt-3.5-turbo-16k-0613
  prompt: prompt/arithmetic/base-9/5-shot_cot_htt_test.yaml
  library: checkpoint/arithmetic/base-9/gpt-3.5_5-shot_cot_htt_2000.yaml
  min_coverage: 2
  min_confidence: 0.5