test:
  dataset: clutrr
  model: gpt-4
  prompt: prompt/clutrr/textual/5-shot_cot_htt_test.yaml
  library: checkpoint/clutrr/symbolic/gpt-4_5-shot_cot_htt_2000.yaml
  min_coverage: 2
  min_confidence: 0.7